// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AgeCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("dob")]
        public DateTimeOffset Dob { get; set; }

        [JsonProperty("age_years")]
        public long AgeYears { get; set; }

        [JsonProperty("age_months")]
        public long AgeMonths { get; set; }

        [JsonProperty("age_weeks")]
        public long AgeWeeks { get; set; }

        [JsonProperty("age_days")]
        public long AgeDays { get; set; }

        [JsonProperty("age_words")]
        public AgeWords AgeWords { get; set; }
    }

    public partial class AgeWords
    {
        [JsonProperty("years")]
        public string Years { get; set; }

        [JsonProperty("ordinal")]
        public string Ordinal { get; set; }

        [JsonProperty("full")]
        public string Full { get; set; }
    }
}
